---
- name: Obtain the infrastructure ID by running
  command: 'oc get -o jsonpath="{.status.infrastructureName}{\"\n\"}" infrastructure cluster'
  register: infra_id

- debug:
    msg: "{{ infra_id.stdout }}"

- set_fact:
    infrastructure_id: "{{ infra_id.stdout }}"
    machinehealcheck_name: "{{ infra_id.stdout }}-{{ role }}-machinehealthcheck"
    machinehealcheck_filename: "{{ infra_id.stdout }}-{{ role }}-machinehealthcheck.yml"
    
- name: Create "{{ yaml_directory_name }}"
  file:
    path: "{{ yaml_directory_name }}"
    state: directory

- name: Create MachineHealthCheck File - "{{ yaml_directory_name }}/{{ machinehealcheck_filename }}"
  template:
    src: machinehealthcheck.yml.j2
    dest: "{{ yaml_directory_name }}/{{ machinehealcheck_filename }}"

- name: Before apply MachineHealthCheck
  command:
    cmd: "oc get machinehealthcheck -n openshift-machine-api"
  register: result

- debug:
    msg: "{{ result.stdout }}"

- name: Apply {{ yaml_directory_name }}/{{ machinehealcheck_filename }}
  command:
    cmd: "oc apply -f {{ yaml_directory_name }}/{{ machinehealcheck_filename }}"
  register: result

- debug:
    msg: "Stdout: {{ result.stdout }}\nStderr: {{ result.stderr }}"

- name: After apply machineset
  command:
    cmd: "oc get machinehealthcheck -n openshift-machine-api"
  register: result

- debug:
    msg: "{{ result.stdout }}"