---
- name: Obtain the infrastructure ID by running
  command: 'oc get -o jsonpath="{.status.infrastructureName}{\"\n\"}" infrastructure cluster'
  register: infra_id

- debug:
    msg: "{{ infra_id.stdout }}"

- set_fact:
    infrastructure_id: "{{ infra_id.stdout }}"
    machineautoscaler_name: "ma-{{ infra_id.stdout }}-{{ role }}"
    machineautoscaler_filename: "ma-{{ infra_id.stdout }}-{{ role }}.yml"

- name: Create "{{ yaml_directory_name }}"
  file:
    path: "{{ yaml_directory_name }}"
    state: directory

- name: Create MachineAutoScaler File - "{{ yaml_directory_name }}/{{ machineautoscaler_filename }}"
  template:
    src: machineautoscaler.yml.j2
    dest: "{{ yaml_directory_name }}/{{ machineautoscaler_filename }}"

- name: Before apply MachineAutoScaler
  command:
    cmd: "oc get machineautoscaler -n openshift-machine-api"
  register: result

- debug:
    msg: "{{ result.stdout }}"

- name: Apply {{ yaml_directory_name }}/{{ machineautoscaler_filename }}
  command:
    cmd: "oc apply -f {{ yaml_directory_name }}/{{ machineautoscaler_filename }}"
  register: result

- debug:
    msg: "Stdout: {{ result.stdout }}\nStderr: {{ result.stderr }}"

- name: After apply machineautoscaler
  command:
    cmd: "oc get machineautoscaler -n openshift-machine-api"
  register: result

- debug:
    msg: "{{ result.stdout }}"
