---
- name: Obtain the infrastructure ID by running
  command: 'oc get -o jsonpath="{.status.infrastructureName}{\"\n\"}" infrastructure cluster'
  register: infra_id

- debug:
    msg: "{{ infra_id.stdout }}"

- set_fact:
    infrastructure_id: "{{ infra_id.stdout }}"

    clusterautoscaler_name: "ca-{{ infra_id.stdout }}-{{ role }}"
    clusterautoscaler_filename: "ca-{{ infra_id.stdout }}-{{ role }}.yml"

- name: Create "{{ yaml_directory_name }}"
  file:
    path: "{{ yaml_directory_name }}"
    state: directory

- name: Create ClusterAutoScaler File - "{{ yaml_directory_name }}/{{ clusterautoscaler_filename }}"
  template:
    src: clusterautoscaler.yml.j2
    dest: "{{ yaml_directory_name }}/{{ clusterautoscaler_filename }}"

- name: Before apply ClusterAutoScaler
  command:
    cmd: "oc get clusterautoscaler -n openshift-machine-api"
  register: result

- debug:
    msg: "{{ result.stdout }}"

- name: Apply {{ yaml_directory_name }}/{{ clusterautoscaler_filename }}
  command:
    cmd: "oc apply -f {{ yaml_directory_name }}/{{ clusterautoscaler_filename }}"
  register: result

- debug:
    msg: "Stdout: {{ result.stdout }}\nStderr: {{ result.stderr }}"

- name: After apply clusterautoscaler
  command:
    cmd: "oc get clusterautoscaler -n openshift-machine-api"
  register: result

- debug:
    msg: "{{ result.stdout }}"